$mod = SUPER

bind = $mod, Return, exec, ghostty
bind = $mod, Q, killactive,
bind = $mod SHIFT, Q, exit
bind = $mod, Space, exec, albert toggle
bind = $mod, Print, exec, flameshot screen -e -n $(hyprctl activeworkspace -j | jq '.monitorID')
bind = $mod SHIFT, Print, exec, screenrecord
bind = $mod, h, movefocus, l
bind = $mod, l, movefocus, r
bind = $mod, k, movefocus, u
bind = $mod, j, movefocus, d

bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 0, movetoworkspace, 10

bind = $mod SHIFT, h, movewindow, l
bind = $mod SHIFT, l, movewindow, r
bind = $mod SHIFT, k, movewindow, u
bind = $mod SHIFT, j, movewindow, d

bind = $mod SHIFT, Space, togglefloating, # Float/Tile
bind = $mod, f, fullscreen,
bind = $mod, t, togglegroup # stack

bind = $mod, r, submap, resize
submap = resize

$resizePx = 40
binde = , l, resizeactive, $resizePx 0
binde = , h, resizeactive, -$resizePx 0
binde = , k, resizeactive, 0 -$resizePx
binde = , j, resizeactive, 0 $resizePx

bind = , escape, submap, reset
submap = reset

# let me control splits
dwindle {
	force_split = 2
	preserve_split = true
}
bind = $mod, v, layoutmsg, preselect r
bind = $mod, b, layoutmsg, preselect d

general {
	gaps_in = 0
	gaps_out = 0
	allow_tearing = true
}

misc {
	middle_click_paste = false
	force_default_wallpaper = 0
	disable_hyprland_logo = true
}

ecosystem {
	no_update_news = true
}

input {
	kb_options = caps:escape
}

cursor {
	persistent_warps = true
}

binds {
	drag_threshold = 10  # Fire a drag event only after dragging for more than 10px
}
bindm = $mod, mouse:272, movewindow # ALT + LMB

# https://gist.github.com/brunoanc/2dea6ddf6974ba4e5d26c3139ffb7580
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = wl-clip-persist --clipboard regular
exec-once = wpaperd -d
exec-once = waybar
exec-once = flameshot
exec-once = albert
# move cursor to center
exec-once = hyprctl dispatch workspace 4

# desktop monitors
$left = DP-3
$center = DP-1
$right = DP-2
monitor = $left, 2560x1440@165, 0x0, 1
monitor = $center, 2560x1440@165, 2560x0, 1
monitor = $right, 2560x1440@165, 5120x0, 1

workspace = 1, monitor:$left
workspace = 2, monitor:$left
workspace = 3, monitor:$left
workspace = 4, monitor:$center
workspace = 5, monitor:$center
workspace = 6, monitor:$center
workspace = 7, monitor:$center
workspace = 8, monitor:$right
workspace = 9, monitor:$right
workspace = 10, monitor:$right

windowrule {
	name = ignore-fullscreen
	match:class = .*
	suppress_event = fullscreen,maximize
}
# windowrule {
# 	name = ignore-float
# 	match:float = 1
# 	float = off
# }

windowrule {
	name = app-launcher
	match:class = albert

	border_size = 0
	no_shadow = on
	dim_around = on
	no_anim = on
	stay_focused = on
}
