#!/bin/bash
# requiredments: curl, tar, jq

set -e

INSTALL_DIR="$HOME/.local/share/zvm"
BIN_DIR="$HOME/.local/bin"

OS="unknown"
case "$OSTYPE" in
  darwin*)        OS="macos" ;;
  linux*)         OS="linux" ;;
  msys*|cygwin*)  OS="windows" ;;
  *)              echo "unknown OSTYPE: $OSTYPE" && exit 1 ;;
esac

ARCH=$(uname -m)
case "$ARCH" in
  arm64)         ARCH="aarch64" ;;
  x86|x86_64)    ;;
  *)             echo "unknown ARCH: $ARCH" && exit 1 ;;
esac

VERSION=$1
ZLS_VERSION=$2

mkdir -p $INSTALL_DIR
pushd $INSTALL_DIR

TRIPLET="zig-$ARCH-$OS-$VERSION"
ARCHIVE="$TRIPLET.tar.xz"
echo "Downloading Zig $VERSION"
curl "https://ziglang.org/download/$VERSION/$ARCHIVE" --output $ARCHIVE
tar -xf $ARCHIVE
rm $ARCHIVE

rm -rf $VERSION
mv $TRIPLET $VERSION

mkdir -p $BIN_DIR
ln -sf $(readlink -f $VERSION/zig) $BIN_DIR/zig

# Relying on latest for now.
# INDEX_URL="https://releases.zigtools.org/v1/zls/select-version?zig_version=$VERSION&compatibility=only-runtime"
# ZLS_URL=$(curl $INDEX_URL | jq ".\"$ARCH-$OS\".tarball" -r)
# ZLS_VERSION=$(echo $ZLS_URL | sed 's:^.*-\(.*\)\.tar\.xz$:\1:')
#
# pushd zls
# mkdir -p $INSTALL_DIR/zls
# ZLS_INSTALL_PATH=$INSTALL_DIR/zls/$ZLS_VERSION
# ARCHIVE="zls-$ARCH-$OS-$ZLS_VERSION"
# echo "Downloading ZLS $ZLS_VERSION"
# curl $ZLS_URL --output $ARCHIVE
# tar -xf $ARCHIVE -C $ZLS_VERSION
# rm $ARCHIVE
#
# ln -sf $(readlink -f $ZLS_VERSION/zls) $BIN_DIR/zls
